server:
  port: ${APP_PORT:3579}

spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:pool:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:naver_news}
    username: ${DB_USER:kimsijun}
    password: ${DB_PASSWORD:1234}
    initialization-mode: always

app:
  poll:
    interval-seconds: ${POLL_INTERVAL_SECONDS:60}
  duplicate:
    threshold: ${DUPLICATED_COUNT:5}

naver:
  openapi:
    url: ${NAVER_OPENAPI_URL:https://openapi.naver.com/v1/search/news.json}
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
  search:
    display: 30
    start: 1
    sort: date

slack:
  webhook:
    breaking: ${BREAKING_NEWS_WEBHOOK_URL}
    exclusive: ${EXCLUSIVE_NEWS_WEBHOOK_URL}
    develop: ${DEVELOP_WEBHOOK_URL}